menu:
  Blog: /
  Archive: /archives
  # Weibo: http://twitter.com
  GitHub: https://github.com/bigfang
  Rss: /atom.xml

favicon: /favicon.ico
logo: /favicon.ico

duoshuo: bigfang

ga: UA-37180058-1

# Copyright Infomation
startyear: 2016
